#!/bin/bash
# .git/hooks/commit-msg

msg_file="$1"
commit_msg="$(<"$msg_file")"

regex="^(feat|fix|chore|docs|style|refactor|test|perf|ci|build|revert) \\( #[0-9]+ \\) : .+$"

if [[ ! $commit_msg =~ $regex ]]; then
  echo "❌ 메시지 형식 에러: 타입 ( #이슈 ) : 설명"
  exit 1
fi

echo "✅ 커밋 메시지 형식 OK"